export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_CUSTOMER_DETAIL = "GET_CUSTOMER_DETAIL";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";
export const SET_LOADING = "SET_LOADING";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
